name: Deploy

on:
  push:
    tags:
      - 'private-*'

env:
  REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
  IMAGE_NAME: ${{ secrets.DOCKER_REGISTRY }}/${{ github.repository }}

jobs:
  deployment:
    runs-on: ubuntu-22.04
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      -
        name: Ping Tailscale
        run: |
          curl ${{ env.REGISTRY }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
          config-inline: |
            [registry."${{ env.REGISTRY }}"]
              http = true
              insecure = true
      -
        name: Build and push to local registry
        uses: docker/build-push-action@v5
        with:
          context: ./web
          file: ./web/Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest
          labels: |
            com.centurylinklabs.watchtower.enable=true
      -
        name: Inspect
        run: |
          docker buildx imagetools inspect ${{ env.IMAGE_NAME }}:latest