services:
  rss-bookmarkr:
    image: rss-bookmarkr
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=${PORT}
    env_file:
      - path: ./.env
        required: true
    extra_hosts:
      - host.docker.internal:host-gateway