services:
  db:
    image: postgres:16.2-bullseye
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mypassword
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      ConnectionStrings__RssDb: Userid=postgres;Password=mypassword;Host=db;Port=5432;Database=postgres;Pooling=true;MinPoolSize=0;MaxPoolSize=100;ConnectionLifetime=0;
      MailSettings__Server: YOUR_MAIL_SERVER_HOST
      MailSettings__Port: 587
      MailSettings__SenderName: YOUR_NAME
      MailSettings__SenderEmail: YOUR@EMAIL
      MailSettings__UserName: YOUR_MAIL_SERVER_USERNAME
      MailSettings__Password: YOUR_MAIL_SERVER_PASWORD
      PUBLIC_HOST: YOUR_PUBLIC_HOST
      ASPNETCORE_URLS: http://[::]:8080
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8080 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      db:
        condition: service_healthy