services:
  db:
    image: postgres:16.2-bullseye
    environment:
      POSTGRES_PASSWORD: mypassword
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  e2e:
    image: ghcr.io/sistracia/rss-bookmarkr-e2e:main
    command: >
      bash -c "dotnet migrondi up --dry-run false
      && npx playwright test -x --reporter list"
    depends_on:
      db:
        condition: service_healthy
